const express = require('express');
const router = express.Router();
const path = require('path');
const fs = require('fs');
const XLSX = require('xlsx');
const db = require('../db');
const { authenticateToken, requirePermission, logAudit } = require('../auth');

const dataDir = path.resolve(__dirname, '..', '..', 'data');
const backupsDir = path.resolve(__dirname, '..', '..', 'backups');
if (!fs.existsSync(backupsDir)) {
  fs.mkdirSync(backupsDir, { recursive: true });
}

// GET /api/backup/daily-excel - Daily Excel Export
router.get('/daily-excel', authenticateToken, requirePermission('backup:export_daily'), (req, res) => {
  const { date_bs } = req.query;
  const todayAd = new Date().toISOString().split('T')[0];

  // Fetch active fiscal year
  const activeFy = db.prepare('SELECT code FROM fiscal_years WHERE is_active = 1 LIMIT 1').get();
  const fyCode = activeFy ? activeFy.code : '2082/83';

  // Target date for backup (default today or specified date)
  const targetDateBs = date_bs || '2082-06-15';

  // Query all voucher lines with metadata
  const rows = db.prepare(`
    SELECT 
      v.voucher_number as 'Voucher No.',
      v.voucher_date_bs as 'Date (BS)',
      v.voucher_date_ad as 'Date (AD)',
      fy.code as 'Fiscal Year',
      vt.code as 'Voucher Type Code',
      vt.title_en as 'Voucher Type',
      v.member_name as 'Member / Party Name',
      v.member_id as 'Member ID',
      ca.account_code as 'Account Code',
      ca.name_en as 'Account Head',
      vl.particulars as 'Particulars',
      vl.debit_amount as 'Debit Amount (Rs.)',
      vl.credit_amount as 'Credit Amount (Rs.)',
      v.payment_mode as 'Payment Mode',
      v.reference_no as 'Reference / Bill No.',
      v.cheque_no as 'Cheque No.',
      v.remarks as 'Remarks',
      u1.full_name_en as 'Prepared By',
      u2.full_name_en as 'Approved By',
      u3.full_name_en as 'Verified By',
      v.status as 'Status',
      v.created_at as 'Created Date Time'
    FROM voucher_lines vl
    JOIN vouchers v ON vl.voucher_id = v.id
    JOIN voucher_types vt ON v.voucher_type_id = vt.id
    JOIN fiscal_years fy ON v.fiscal_year_id = fy.id
    JOIN chart_of_accounts ca ON vl.account_id = ca.id
    JOIN users u1 ON v.prepared_by = u1.id
    LEFT JOIN users u2 ON v.approved_by = u2.id
    LEFT JOIN users u3 ON v.verified_by = u3.id
    ORDER BY v.id ASC, vl.line_order ASC
  `).all();

  // Create Excel workbook using XLSX
  const wb = XLSX.utils.book_new();

  // Worksheet 1: Detailed Voucher Lines
  const wsDetails = XLSX.utils.json_to_sheet(rows.length > 0 ? rows : [{ Message: 'No transactions found.' }]);
  XLSX.utils.book_append_sheet(wb, wsDetails, 'Vouchers Detail');

  // Worksheet 2: Summary Stats
  const totalDebit = rows.reduce((s, r) => s + (r['Debit Amount (Rs.)'] || 0), 0);
  const totalCredit = rows.reduce((s, r) => s + (r['Credit Amount (Rs.)'] || 0), 0);
  const uniqueVouchers = new Set(rows.map(r => r['Voucher No.'])).size;

  const summaryData = [
    { Indicator: 'Organization Name', Value: 'Positive Saving & Credit Co-operative Ltd.' },
    { Indicator: 'Backup Generated Date', Value: `${todayAd} (BS: ${targetDateBs})` },
    { Indicator: 'Active Fiscal Year', Value: fyCode },
    { Indicator: 'Total Unique Vouchers', Value: uniqueVouchers },
    { Indicator: 'Total Debit Turnover (Rs.)', Value: totalDebit },
    { Indicator: 'Total Credit Turnover (Rs.)', Value: totalCredit },
    { Indicator: 'Generated By', Value: req.user.username + ` (${req.user.fullNameEn})` }
  ];
  const wsSummary = XLSX.utils.json_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  // Standard naming convention requested by master prompt:
  // e.g. PSCCL_Voucher_Backup_2083-06-30.xlsx
  const fileName = `PSCCL_Voucher_Backup_${targetDateBs}.xlsx`;
  const filePath = path.join(backupsDir, fileName);

  XLSX.writeFile(wb, filePath);

  const fileStats = fs.statSync(filePath);

  // Log in backup_logs
  db.prepare(`
    INSERT INTO backup_logs (backup_type, file_name, file_path, file_size, records_count, created_by)
    VALUES (?, ?, ?, ?, ?, ?)
  `).run('DAILY_EXCEL', fileName, filePath, fileStats.size, rows.length, req.user.id);

  logAudit('BACKUP', fileName, 'EXPORT_DAILY_EXCEL', req, {
    records_count: rows.length,
    file_name: fileName,
    total_volume: totalDebit
  });

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
  return res.download(filePath, fileName);
});

// GET /api/backup/db-snapshot - Download SQLite Database Snapshot
router.get('/db-snapshot', authenticateToken, requirePermission('backup:manage_db'), (req, res) => {
  const dbSource = path.join(dataDir, 'positive_saccos.db');
  if (!fs.existsSync(dbSource)) {
    return res.status(404).json({ success: false, error: 'Database file not found.' });
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const snapshotName = `PSCCL_Database_Snapshot_${timestamp}.db`;
  const snapshotPath = path.join(backupsDir, snapshotName);

  // Safely copy database file
  fs.copyFileSync(dbSource, snapshotPath);
  const fileStats = fs.statSync(snapshotPath);

  db.prepare(`
    INSERT INTO backup_logs (backup_type, file_name, file_path, file_size, records_count, created_by)
    VALUES (?, ?, ?, ?, ?, ?)
  `).run('DB_SNAPSHOT', snapshotName, snapshotPath, fileStats.size, 0, req.user.id);

  logAudit('BACKUP', snapshotName, 'DB_SNAPSHOT_DOWNLOAD', req, { file_name: snapshotName });

  res.setHeader('Content-Type', 'application/octet-stream');
  res.setHeader('Content-Disposition', `attachment; filename="${snapshotName}"`);
  return res.download(snapshotPath, snapshotName);
});

// GET /api/backup/history - List backup logs
router.get('/history', authenticateToken, requirePermission('backup:export_daily'), (req, res) => {
  const logs = db.prepare(`
    SELECT b.*, u.full_name_en as created_by_name
    FROM backup_logs b
    LEFT JOIN users u ON b.created_by = u.id
    ORDER BY b.id DESC
    LIMIT 30
  `).all();

  return res.json({ success: true, history: logs });
});

module.exports = router;
